local _, NS = ...
-- Curated Forever beta guide, reviewed 2026-09-25. See docs/pet-guide-sources.md.
-- These are family recommendations, NOT this creature's innate/teachable skills.
-- Numeric keys are creature family/NPC IDs, never IDs used for spell detection.
local DB={reviewed='2026-09-25',version='Forever 1.60.1 beta',families={},notable={},rareByID={},rareByName={}}
NS.PetDatabase=DB
local function Family(id,name,role,ability,effect)
    DB.families[id]={name=name,role=role,ability=ability,effect=effect}
end
Family(1,'Wolf','Group melee support','Furious Howl','Party melee attack power buff.')
Family(2,'Cat','Single-target damage / stealth','Claw / Prowl','Direct damage; stealth approach when trained.')
-- A player observed several Forever spiders, including ROL spiders, without Web.
-- Do not infer any target skill from family identity.
Family(3,'Spider','Varies by individual pet',nil,nil)
Family(4,'Bear','Solo multi-target fighting','Swipe / Savage Rend','Multi-target attack; bleed support.')
Family(5,'Boar','Solo pulls / closing gaps','Rushing Charge','Burst movement and a stronger opening attack.')
Family(6,'Crocolisk','PvP healing pressure','Dismember','Damage with reduced healing received.')
Family(7,'Carrion Bird','Bleed-focused group support','Savage Rend','Bleed damage and increased bleed damage taken.')
Family(8,'Crab','PvP control / kiting','Pinch','Damage with a movement slow.')
Family(9,'Gorilla','Solo multi-target fighting','Thunderstomp','Area damage around the pet.')
Family(11,'Raptor','Bleed-focused damage','Savage Rend','Bleed damage and increased bleed damage taken.')
Family(12,'Tallstrider','Physical-damage group support','Dust Cloud','Armor reduction on the enemy.')
Family(20,'Scorpid','Sustained poison pressure','Scorpid Poison','Nature damage over time.')
Family(21,'Turtle','Solo pet survival','Shell Shield','Defensive damage reduction.')
Family(24,'Bat','Mobile damage','Bite / Dive','Direct damage and movement speed when trained.')
Family(25,'Hyena','PvP control / kiting','Tendon Rip','Damage over time with a movement slow.')
Family(26,'Owl / Bird of Prey','Control against weapon users','Mine!','Damage with a short disarm.')
Family(27,'Wind Serpent','Ranged Nature damage','Lightning Breath','Pet damage from outside melee range.')
Family(312,'Core Hound','Pressure against casters','Lava Breath','Fire damage and slower enemy casting; beta tame sources unconfirmed.')
Family(319,'Fox','Short bursts / pet survival',"Trickster's Dance",'Temporary dodge and faster attacks; beta tame sources unconfirmed.')
-- A small watch list, not a complete roster or a guarantee of tameability.
local function Notable(id,name,family,zone)
    DB.notable[id]={name=name,family=family,zone=zone}
end
Notable(5807,'The Rake',2,'Mulgore')
Notable(2850,'Broken Tooth',2,'Badlands')
Notable(14430,'Duskstalker',2,'Teldrassil')
Notable(3619,'Ghost Saber',2,'Darkshore')
Notable(731,'King Bangalash',2,'Stranglethorn Vale')
Notable(5823,'Death Flayer',20,'Durotar')
Notable(3068,'Mazzranache',12,'Mulgore')
Notable(10357,'Ressan the Needler',24,'Tirisfal Glades')
Notable(4425,'Blind Hunter',24,'Razorfen Kraul')
Notable(521,'Lupos',1,'Duskwood')
Notable(1132,'Timber',1,'Dun Morogh')
Notable(5356,'Snarler',1,'Feralas')
Notable(10077,'Deathmaw',1,'Burning Steppes')
Notable(9696,'Bloodaxe Worg',1,'Blackrock Spire')
Notable(8211,'Old Cliff Jumper',1,'The Hinterlands')
Notable(1130,'Bjarn',4,'Dun Morogh')
Notable(12037,"Ursol'lok",4,'Ashenvale')
Notable(3581,'Sewer Beast',6,'Stormwind City')
Notable(8213,'Ironback',21,'The Hinterlands')
Notable(14223,'Cranky Benj',21,'Alterac Mountains')
Notable(4887,'Ghamoo-ra',21,'Blackfathom Deeps')
-- Forever rare roster. Owned pets cannot reliably expose their original NPC ID,
-- so exact English name + live family is used as a guarded origin hint.
local function Rare(id,name,family,zone,level)
    local entry={id=id,name=name,family=family,zone=zone,level=level}
    if id then DB.rareByID[id]=entry end
    DB.rareByName[name]=entry
end
Rare(1132,'Timber',1,'Dun Morogh',10)
Rare(nil,'Coldrasp',1,'Tirisfal Glades',12)
Rare(12431,'Gorefang',1,'Silverpine Forest',13)
Rare(10644,'Mist Howler',1,'Ashenvale',22)
Rare(521,'Lupos',1,'Duskwood',23)
Rare(2753,'Barnabus',1,'Badlands',38)
Rare(8211,'Old Cliff Jumper',1,'The Hinterlands',42)
Rare(5356,'Snarler',1,'Feralas',42)
Rare(14339,'Death Howl',1,'Felwood',49)
Rare(10077,'Deathmaw',1,'Burning Steppes',53)
Rare(14430,'Duskstalker',2,'Teldrassil',9)
Rare(nil,'Shal\'ma',2,'Durotar',9)
Rare(5807,'The Rake',2,'Mulgore',10)
Rare(5865,'Dishu',2,'The Barrens',13)
Rare(2175,'Shadowclaw',2,'Darkshore',13)
Rare(nil,'Ghostfang',2,'Dun Morogh',17)
Rare(5828,'Humar The Pridelord',2,'The Barrens',23)
Rare(14222,'Araga',2,'Alterac Mountains',35)
Rare(2850,'Broken Tooth',2,'Badlands',37)
Rare(10200,'Rak\'Shiri',2,'Winterspring',57)
Rare(471,'Mother Fang',3,'Elwynn Forest',10)
Rare(10359,'Sri\'skulk',3,'Tirisfal Glades',13)
Rare(12433,'Krethis Shadowspinner',3,'Silverpine Forest',15)
Rare(14266,'Shanda the Spinner',3,'Loch Modan',19)
Rare(616,'Chatter',3,'Redridge Mountains',23)
Rare(14279,'Creepthess',3,'Hillsbrad Foothills',24)
Rare(1112,'Leech Widow',3,'Wetlands',24)
Rare(574,'Naraxis',3,'Duskwood',27)
Rare(4380,'Darkmist Widow',3,'Dustwallow Marsh',40)
Rare(8277,'Rekk\'tilac',3,'Searing Gorge',48)
Rare(14472,'Gretheer',3,'Silithus',57)
Rare(1130,'Bjarn',4,'Dun Morogh',12)
Rare(nil,'Mystmane',4,'Zephras Isle',13)
Rare(12432,'Old Vicejaw',4,'Silverpine Forest',14)
Rare(14280,'Big Samras',4,'Hillsbrad Foothills',27)
Rare(12037,'Ursol\'lok',4,'Ashenvale',31)
Rare(5352,'Old Grizzlegut',4,'Feralas',43)
Rare(14344,'Mongress',4,'Felwood',50)
Rare(8303,'Grunter',5,'Blasted Lands',50)
Rare(2476,'Large Loch Crocolisk',6,'Loch Modan',22)
Rare(14233,'Ripscale',6,'Dustwallow Marsh',39)
Rare(3581,'Sewer Beast',6,'Stormwind City',50)
Rare(14268,'Lord Condar',7,'Loch Modan','15-16')
Rare(462,'Vultros',7,'Westfall',26)
Rare(8207,'Greater Firebird',7,'Tanaris',46)
Rare(8299,'Spiteflayer',7,'Blasted Lands',52)
Rare(2931,'Zaricotl',7,'Badlands',55)
Rare(14491,'Kurmokk',9,'Stranglethorn Vale',42)
Rare(6585,'Uhk\'loc',9,'Un\'Goro Crater',52)
Rare(5842,'Takk the Leaper',11,'The Barrens',19)
Rare(1140,'Razormaw Matriarch',11,'Wetlands',31)
Rare(14232,'Dart',11,'Dustwallow Marsh',38)
Rare(3068,'Mazzranache',12,'Mulgore',9)
Rare(2172,'Strider Clutchmother',12,'Darkshore',20)
Rare(5823,'Death Flayer',20,'Durotar',11)
Rare(5937,'Vile Sting',20,'Thousand Needles',35)
Rare(8301,'Clack the Reaver',20,'Blasted Lands',53)
Rare(14476,'Krellack',20,'Silithus',56)
Rare(14223,'Cranky Benj',21,'Alterac Mountains',32)
Rare(8213,'Ironback',21,'The Hinterlands',51)
Rare(10357,'Ressan the Needler',24,'Tirisfal Glades',11)
Rare(4425,'Blind Hunter',24,'Razorfen Kraul (Dungeon)',32)
Rare(5829,'Snort the Heckler',25,'The Barrens',17)
Rare(14228,'Giggler',25,'Desolace',34)
Rare(8208,'Murderous Blisterpaw',25,'Tanaris',43)
Rare(8300,'Ravage',25,'Blasted Lands',51)
Rare(14343,'Olm the Wise',26,'Felwood',52)
Rare(5834,'Azzere the Skyblade',27,'The Barrens',25)
Rare(14234,'Hayoc',27,'Dustwallow Marsh',41)
Rare(5349,'Arash-ethis',27,'Feralas',49)
-- Only used when the client does not return a family ID. ID matching is localized.
DB.familyNames={}
for id,family in pairs(DB.families) do DB.familyNames[family.name]=id end
DB.familyNames.Owl=26;DB.familyNames['Bird of Prey']=26
